### PR TITLE
[Exam sheet] University logo and reorganisation

### PR DESCRIPTION
**Pull request by alex-mitrevski**
This pull request modifies the generation of the exam sheet (i.e. the sheet with student exam login information and space for writing the submission hash code/time stamp).

The following modifications and additions are included:
* The university logo is added to the top of the sheet (since it's an official document for the examination)
* The course name and the semester info are moved just below the logo instead of being at the very bottom
* General code cleanup and documentation
* Renamed the directory `create_multiple_users` to `exam_user_utilities` to better reflect the contents

The updated exam sheet looks as shown below:

exam_sheet_updated

### CODE REVIEW

**Comment by mhwasil** [comment]
I used tool_walkthrough.ipynb to try all new features using notebook instead of python file. For me, it was easier to develope new features on the notebook :). But once it's finalized, it should be moved to the corresponding directory.

The final version of exam sheet generation has been moved [here](https://github.com/DigiKlausur/brsu_digital_exam_tools/blob/master/create_multiple_users/convert_student_list_to_pdf.py),
along with the example of CSV file containing student data and the sampe of examination sheet. Can you also update  [this](https://github.com/DigiKlausur/brsu_digital_exam_tools/blob/master/create_multiple_users/convert_student_list_to_pdf.py) and use the same sample?

Regarding the header of the header of the csv, the [bulk user generation](https://github.com/DigiKlausur/brsu_digital_exam_tools/blob/master/create_multiple_users/create_bulk_users.sh) currently does not work if the csv contains header. I will add this as an issue.

**Comment by alex-mitrevski** [comment]
@mhwasil You merged before I could update the documentation. :)

An example call for the script is given below

```
python3 generate_student_exam_sheets.py -i exam_user_utilities/samples/exam_complete_list_output.csv -o exam_user_utilities/samples/exam_complete_list_output.csv -c 'My awesome course' -s 'Sommersemester 2019'
```

Could you add it or would you like me to create another PR with the update?

**Comment by mhwasil** [comment]
Ups, sorry. I will update the documentation.

**Comment by alex-mitrevski** [comment]
Great, thanks!

**Pull request merged**
